package races

var RacesJsonData = []byte(`[
   {
      "race_name":"Aasimar",
      "race_name_ru":"Аасимар",
      "type":[
         {
            "type_race_name":"Aasimar",
            "type_race_name_ru":"Аасимар",
            "stats_up":{
               "strength":0,
               "dexterity":0,
               "body_difficulty":0,
               "intelligence":0,
               "wisdom":0,
               "charisma":2
            }
         },
         {
            "type_race_name":"",
            "type_race_name_ru":"Aasimar Defender",
            "stats_up":{
               "strength":0,
               "dexterity":0,
               "body_difficulty":0,
               "intelligence":0,
               "wisdom":1,
               "charisma":0
            }
         },
         {
            "type_race_name":"Aasimar the Punisher",
            "type_race_name_ru":"Аасимар–каратель",
            "stats_up":{
               "strength":0,
               "dexterity":0,
               "body_difficulty":1,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         },
         {
            "type_race_name":"Aasimar the fallen",
            "type_race_name_ru":"Аасимар–падший",
            "stats_up":{
               "strength":1,
               "dexterity":0,
               "body_difficulty":0,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         }
      ],
      "min_age":18,
      "max_age":160,
      "min_height":150,
      "max_height":180,
      "min_weight":70,
      "max_weight":90,
      "speed":30,
      "langs":[
         "Общий",
         "Небесный"
      ],
      "race_skill":"",
      "names":{
         "man":[
            
         ],
         "woman":[
            
         ]
      },
      "last_names":[
         
      ],
      "resist":[
         "урону излучением",
         "некротической энергией"
      ]
   },
   {
      "race_name":"Bugbear",
      "race_name_ru":"Багбир",
      "type":[
         {
            "type_race_name":"Bugbear",
            "type_race_name_ru":"Багбир",
            "stats_up":{
               "strength":2,
               "dexterity":1,
               "body_difficulty":0,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         }
      ],
      "min_age":16,
      "max_age":80,
      "min_height":150,
      "max_height":180,
      "min_weight":70,
      "max_weight":90,
      "speed":30,
      "langs":[
         "Общий",
         "Гоблинский"
      ],
      "race_skill":"Скрытность",
      "names":{
         "man":[
            "Аругет",
            "Четин",
            "Даавн",
            "Дабрак",
            "Дагии",
            "Древдуул",
            "Дуулан",
            "Феник",
            "Гудруун",
            "Халуун",
            "Харуук",
            "Джазаал",
            "Каллаад",
            "Кракуул",
            "Кроотад",
            "Мазаан",
            "Мунта",
            "Насаар",
            "Ракари",
            "Рексиит",
            "Тарик",
            "Тарууж",
            "Туун",
            "Вании",
            "Ванон",
            "Вуударадж"
         ],
         "woman":[
            "Ааспар",
            "Агуус",
            "Белалуур",
            "Денаал",
            "Драраар",
            "Дууша",
            "Эхаас",
            "Элуун",
            "Грааль",
            "Гадуул",
            "Хашак",
            "Джелуум",
            "Келаал",
            "Мулаан",
            "Насри",
            "Ралин",
            "Разу",
            "Рексин",
            "Сенен",
            "Шедруор",
            "Таджин",
            "Тюнер",
            "Вали",
            "Вуун"
         ]
      },
      "last_names":[
         
      ],
      "resist":[
         
      ]
   },
   {
      "race_name":"Gnome",
      "race_name_ru":"Гном",
      "type":[
         {
            "type_race_name":"Gnome",
            "type_race_name_ru":"Гном",
            "stats_up":{
               "strength":0,
               "dexterity":0,
               "body_difficulty":0,
               "intelligence":2,
               "wisdom":0,
               "charisma":0
            }
         },
         {
            "type_race_name":"FOREST GNOME",
            "type_race_name_ru":"ЛЕСНОЙ ГНОМ",
            "stats_up":{
               "strength":0,
               "dexterity":1,
               "body_difficulty":0,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         },
         {
            "type_race_name":"ROCK DWARF",
            "type_race_name_ru":"СКАЛЬНЫЙ ГНОМ",
            "stats_up":{
               "strength":0,
               "dexterity":0,
               "body_difficulty":1,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         }
      ],
      "min_age":25,
      "max_age":250,
      "min_height":90,
      "max_height":120,
      "min_weight":15,
      "max_weight":20,
      "speed":25,
      "langs":[
         "Общий",
         "Гномий"
      ],
      "race_skill":"",
      "names":{
         "man":[
            "Алвин",
            "Алстон",
            "Боддинок",
            "Брок",
            "Бюргел",
            "Варрин",
            "Вренн",
            "Гербо",
            "Гимбл",
            "Глим",
            "Джебеддо",
            "Димбл",
            "Зук",
            "Келлен",
            "Намфудл",
            "Оррин",
            "Рундар",
            "Сибо",
            "Синдри",
            "Фонкин",
            "Фрюг",
            "Элдон",
            "Эрки"
         ],
         "woman":[
            "Бимпноттин",
            "Брина",
            "Вейуокет",
            "Донелла",
            "Дувамил",
            "Занна",
            "Карамип",
            "Карлин",
            "Лилли",
            "Лорилла",
            "Лупмоттин",
            "Маднаб",
            "Никс",
            "Нисса",
            "Ода",
            "Орла",
            "Ройвин",
            "Тана",
            "Шамил",
            "Эливик",
            "Элиджобелл",
            "Элла"
         ]
      },
      "last_names":[
         "Берен",
         "Гаррик",
         "Даергел",
         "Мёрниг",
         "Накл",
         "Нингел",
         "Раулнор",
         "Тимберс",
         "Турен",
         "Фолькор",
         "Шеппен"
      ],
      "resist":[
         
      ]
   },
   {
      "race_name":"Goblin",
      "race_name_ru":"Гоблин",
      "type":[
         {
            "type_race_name":"Goblin",
            "type_race_name_ru":"Гоблин",
            "stats_up":{
               "strength":0,
               "dexterity":2,
               "body_difficulty":1,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         },
         {
            "type_race_name":"DUNKWOOD GOBLINS",
            "type_race_name_ru":"ГОБЛИНЫ ДАНКВУДА",
            "stats_up":{
               "strength":0,
               "dexterity":2,
               "body_difficulty":0,
               "intelligence":0,
               "wisdom":1,
               "charisma":0
            }
         }
      ],
      "min_age":8,
      "max_age":60,
      "min_height":120,
      "min_weight":36,
      "speed":30,
      "langs":[
         "Гоблинский",
         "Общий"
      ],
      "race_skill":"",
      "names":{
         "man":[
            "Аругет",
            "Вании",
            "Ванон",
            "Вуударадж",
            "Гудруун",
            "Даавн",
            "Дабрак",
            "Дагии",
            "Джазаал",
            "Древдуул",
            "Дуулан",
            "Каллаад",
            "Кракуул",
            "Кроотад",
            "Мазаан",
            "Мунта",
            "Насаар",
            "Ракари",
            "Рексиит",
            "Тарик",
            "Тарууж",
            "Туун",
            "Феник",
            "Четин",
            "Халуун",
            "Харуук"
         ],
         "woman":[
            "Ааспар",
            "Агуус",
            "Белалуур",
            "Вали",
            "Вуун",
            "Грааль",
            "Гадуул",
            "Денаал",
            "Джелуум",
            "Драраар",
            "Дууша",
            "Келаал",
            "Мулаан",
            "Разу",
            "Ралин",
            "Рексин",
            "Сенен",
            "Таджин",
            "Тюнер",
            "Хашак",
            "Шедруор",
            "Эхаас",
            "Элуун"
         ]
      },
      "last_names":[
         
      ],
      "resist":[
         
      ]
   },
   {
      "race_name":"Goliath",
      "race_name_ru":"Голиаф",
      "type":[
         {
            "type_race_name":"Goliath",
            "type_race_name_ru":"Голиаф",
            "stats_up":{
               "strength":2,
               "dexterity":0,
               "body_difficulty":1,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         }
      ],
      "min_age":22,
      "max_age":90,
      "min_height":210,
      "max_height":250,
      "min_weight":125,
      "max_weight":160,
      "speed":30,
      "langs":[
         "Общий",
         "Язык Великанов"
      ],
      "race_skill":"Атлетика",
      "names":{
         "man":[
            "Аукан 'Бесстрашный'",
            "Вимак 'Дважды осиротевший'",
            "Гае-Ал 'Прядильщик'",
            "Иглат 'Резчик рогов'",
            "Иликан 'Одинокий охотник'",
            "Кеотхи 'Красиво говорящий'",
            "Куори 'Кривые руки'",
            "Ло-Каг 'Умелый прыгун'",
            "Мавейт 'Смотрящий в небо'",
            "Маннео 'Встающий с рассветом'",
            "Орило 'Кипящий'",
            "Пааву 'Крадущийся быстро'",
            "Петани 'Олицетрворение силы'",
            "Талай 'Идущий к реке'",
            "Тхотам 'Разрубивший корни'",
            "Утхал 'Искатель кремня'"
         ],
         "woman":[
            "Арлла Зоркий глаз",
            "Ваунеа 'Твёрдая рука'",
            "Нарла Великая",
            "Налла 'Убийца медведей'"
         ]
      },
      "last_names":[
         
      ],
      "resist":[
         "Холоду"
      ]
   },
   {
      "race_name":"Dwarf",
      "race_name_ru":"Дварф ",
      "type":[
         {
            "type_race_name":"Mountain Dwarf",
            "type_race_name_ru":"Горный Дварф",
            "stats_up":{
               "strength":2,
               "dexterity":0,
               "body_difficulty":2,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         },
         {
            "type_race_name":"Hill Dwarf",
            "type_race_name_ru":"Холмовой Дварф",
            "stats_up":{
               "strength":0,
               "dexterity":0,
               "body_difficulty":2,
               "intelligence":0,
               "wisdom":1,
               "charisma":0
            }
         },
         {
            "type_race_name":"Dwarf Duergar",
            "type_race_name_ru":"Дварф Дуэргар",
            "stats_up":{
               "strength":1,
               "dexterity":0,
               "body_difficulty":2,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         }
      ],
      "min_age":50,
      "max_age":360,
      "min_height":120,
      "max_height":155,
      "min_weight":60,
      "max_weight":75,
      "speed":25,
      "langs":[
         "Общий",
         "Дварфийский"
      ],
      "race_skill":"История",
      "names":{
         "man":[
            "Адрик",
            "Альберих",
            "Баренд",
            "Баэрн",
            "Броттор",
            "Бруенор",
            "Вондал",
            "Вэйт",
            "Гардаин",
            "Даин",
            "Даррак",
            "Делг",
            "Килдрак",
            "Моргран",
            "Орсик",
            "Оскар",
            "Рангрим",
            "Рюрик",
            "Таклинн",
            "Торадин",
            "Тордек",
            "Торин",
            "Травок",
            "Траубон",
            "Ульфгар",
            "Фаргрим",
            "Флинт",
            "Харбек",
            "Эберк",
            "Эйнкиль"
         ],
         "woman":[
            "Артин",
            "Бардрин",
            "Вистра",
            "Гуннлода",
            "Гурдис",
            "Дагнал",
            "Диеза",
            "Илде",
            "Кристид",
            "Лифтраса",
            "Мардред",
            "Одхильд",
            "Рисвин",
            "Саннл",
            "Торбера",
            "Торгга",
            "Фалкрунн",
            "Финеллен",
            "Хельджа",
            "Хлин",
            "Эльдет",
            "Эмбер"
         ]
      },
      "last_names":[
         "Балдерк",
         "Боевой Молот",
         "Горунн",
         "Данкил",
         "Железный Кулак",
         "Крепкая Наковальня",
         "Ледяная Борода",
         "Лодерр",
         "Лютгер",
         "Огненная Кузня",
         "Рамнахейм",
         "Стракелн",
         "Торунн",
         "Унгарт",
         "Холдерхек"
      ],
      "resist":[
         "Ядом"
      ]
   },
   {
      "race_name":"Kenku",
      "race_name_ru":"Кенку",
      "type":[
         {
            "type_race_name":"Kenku",
            "type_race_name_ru":"Кенку",
            "stats_up":{
               "strength":0,
               "dexterity":2,
               "body_difficulty":0,
               "intelligence":0,
               "wisdom":1,
               "charisma":0
            }
         }
      ],
      "min_age":12,
      "max_age":60,
      "min_height":140,
      "max_height":155,
      "min_weight":40,
      "max_weight":55,
      "speed":30,
      "langs":[
         "Общий",
         "Ауране (воздушный диалект Первичного)"
      ],
      "race_skill":[
         "Акробатика",
         "Обман",
         "Скрытность",
         "Ловкость рук"
      ],
      "names":{
         "man":[
            
         ],
         "woman":[
            
         ]
      },
      "last_names":[
         
      ],
      "resist":[
         
      ]
   },
   {
      "race_name":"Kobold",
      "race_name_ru":"Кобольд",
      "type":[
         {
            "type_race_name":"Kobold",
            "type_race_name_ru":"Кобольд",
            "stats_up":{
               "strength":0,
               "dexterity":2,
               "body_difficulty":0,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         }
      ],
      "min_age":6,
      "max_age":100,
      "min_height":60,
      "max_height":95,
      "min_weight":11,
      "max_weight":15,
      "speed":30,
      "langs":[
         "Общий",
         "Драконий"
      ],
      "race_skill":"",
      "names":{
         "man":[
            
         ],
         "woman":[
            
         ]
      },
      "last_names":[
         
      ],
      "resist":[
         
      ]
   },
   {
      "race_name":"Locathah",
      "race_name_ru":"Локата",
      "type":[
         {
            "type_race_name":"Locathah",
            "type_race_name_ru":"Локата",
            "stats_up":{
               "strength":2,
               "dexterity":1,
               "body_difficulty":0,
               "intelligence":0,
               "wisdom":0,
               "charisma":0
            }
         }
      ],
      "min_age":6,
      "max_age":100,
      "min_height":150,
      "max_height":195,
      "min_weight":60,
      "max_weight":75,
      "speed":30,
      "langs":[
         "Акван",
         "Общий"
      ],
      "race_skill":[
         "Восприятие",
         "Атлетика"
      ],
      "names":{
         "man":[
            
         ],
         "woman":[
            
         ]
      },
      "last_names":[
         
      ],
      "resist":[
         
      ]
   }
]`)
