package classes

var RaceCharactsJsonData = []byte(`{
   "data":[
      {
         "charReq":[
            [
               "Intelligence",
               "BodyDifficulty",
               "Charisma"
            ],
            [
               "Intelligence",
               "Dexterity",
               "Charisma"
            ],
            [
               "Intelligence",
               "Wisdom",
               "Charisma"
            ]
         ],
         "className":"Wizard",
         "background":[
            "Guild artisan",
            "Sage",
            "Soldier",
            "Folk hero"
         ]
      },
      {
         "charReq":[
            [
               "Intelligence",
               "Dexterity",
               "BodyDifficulty"
            ],
            [
               "Intelligence",
               "Dexterity",
               "Wisdom"
            ]
         ],
         "className":"Alchemist",
         "background":[
            "Noble",
            "Guild artisan",
            "Soldier"
         ]
      },
      {
         "charReq":[
            [
               "Strength",
               "Dexterity",
               "Intelligence"
            ],
            [
               "Strength",
               "Dexterity",
               "BodyDifficulty"
            ],
            [
               "Strength",
               "Dexterity",
               "Charisma"
            ]
         ],
         "className":"Fighter",
         "background":[
            "Urchin",
            "Noble",
            "Sailor",
            "Knight",
            "Folk hero",
            "Soldier",
            "Outlander"
         ]
      },
      {
         "charReq":[
            [
               "Strength",
               "BodyDifficulty",
               "Wisdom"
            ],
            [
               "Strength",
               "BodyDifficulty",
               "Charisma"
            ],
            [
               "Strength",
               "BodyDifficulty",
               "Intelligence"
            ]
         ],
         "className":"Barbarian",
         "background":[
            "Sailor",
            "Folk hero",
            "Pirate",
            "Soldier",
            "Outlander"
         ]
      },
      {
         "charReq":[
            [
               "Strength",
               "Charisma",
               "BodyDifficulty"
            ],
            [
               "Strength",
               "Charisma",
               "Wisdom"
            ]
         ],
         "className":"Paladin",
         "background":[
            "Noble",
            "Hermit",
            "Soldier"
         ]
      },
      {
         "charReq":[
            [
               "Dexterity",
               "Wisdom",
               "Strength"
            ]
         ],
         "className":"Monk",
         "background":[
            "Folk hero",
            "Hermit",
            "Acolyte"
         ]
      },
      {
         "charReq":[
            [
               "Dexterity",
               "BodyDifficulty",
               "Charisma"
            ],
            [
               "Dexterity",
               "BodyDifficulty",
               "Wisdom"
            ]
         ],
         "className":"Alternative Monk",
         "background":[
            "Sage",
            "Hermit",
            "Criminal",
            "Acolyte",
            "Soldier",
            "Outlander",
            "Charlatan"
         ]
      },
      {
         "charReq":[
            [
               "Dexterity",
               "Intelligence",
               "Charisma"
            ],
            [
               "Dexterity",
               "Intelligence",
               "Wisdom"
            ]
         ],
         "className":"Rogue",
         "background":[
            "Urchin",
            "Pirate",
            "Criminal",
            "Charlatan",
            "Outlander"
         ]
      },
      {
         "charReq":[
            [
               "Dexterity",
               "Wisdom",
               "Charisma"
            ],
            [
               "Strength",
               "Wisdom",
               "Dexterity"
            ]
         ],
         "className":"Ranger",
         "background":[
            "Guild artisan",
            "Folk hero",
            "Criminal",
            "Outlander"
         ]
      },
      {
         "charReq":[
            [
               "Wisdom",
               "BodyDifficulty",
               "Dexterity"
            ]
         ],
         "className":"Druid",
         "background":[
            "Guild artisan",
            "Folk hero",
            "Hermit",
            "Acolyte",
            "Outlander"
         ]
      },
      {
         "charReq":[
            [
               "Wisdom",
               "BodyDifficulty",
               "Strength"
            ],
            [
               "Wisdom",
               "BodyDifficulty",
               "Intelligence"
            ]
         ],
         "className":"Shaman",
         "background":[
            "Urchin",
            "Noble",
            "Guild artisan",
            "Sailor",
            "Sage",
            "Folk hero",
            "Hermit",
            "Pirate",
            "Criminal",
            "Acolyte",
            "Soldier",
            "Outlander",
            "Charlatan"
         ]
      },
      {
         "charReq":[
            [
               "Wisdom",
               "BodyDifficulty",
               "Charisma"
            ],
            [
               "Wisdom",
               "Strength",
               "Charisma"
            ]
         ],
         "className":"Cleric",
         "background":[
            "Sage",
            "Folk hero",
            "Hermit",
            "Acolyte",
            "Charlatan"
         ]
      },
      {
         "charReq":[
            [
               "Charisma",
               "BodyDifficulty",
               "Wisdom"
            ]
         ],
         "className":"Warlock",
         "background":[
            "Hermit",
            "Sage",
            "Charlatan"
         ]
      },
      {
         "charReq":[
            [
               "Charisma",
               "BodyDifficulty",
               "Intelligence"
            ]
         ],
         "className":"Sorcerer",
         "background":[
            "Guild artisan",
            "Sage",
            "Folk hero",
            "Hermit"
         ]
      },
      {
         "charReq":[
            [
               "Charisma",
               "Dexterity",
               "Wisdom"
            ],
            [
               "Charisma",
               "Dexterity",
               "BodyDifficulty"
            ],
            [
               "Charisma",
               "Dexterity",
               "Intelligence"
            ]
         ],
         "className":"Bard",
         "background":[
            "Artist",
            "Noble",
            "Urchin",
            "Charlatan"
         ]
      }
   ,
      {
         "charReq":[
            [
               "Intelligence",
               "BodyDifficulty",
               "Wisdom"
            ],
            [
               "Intelligence",
               "BodyDifficulty",
               "Dexterity"
            ]
         ],
         "className":"Artificer",
         "background":[
            "Guild artisan",
            "Sage",
            "Folk hero"
         ]
      }
   ]
}`)
